---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/konflux-ci/konflux-ci/dependencies/keycloak/crd?ref=f74fcb33e86e9cef3062f815ad9190206ff28526
  - https://github.com/konflux-ci/konflux-ci/dependencies/keycloak/deployment?ref=f74fcb33e86e9cef3062f815ad9190206ff28526

