apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
spec:
  generators:
    - clusters:
        values:
          sourceRoot: components/cert-manager
          environment: staging
          clusterDir: ""
  template:
    metadata:
      name: cert-manager-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/{{values.environment}}/{{values.clusterDir}}'
        repoURL: https://github.com/konflux-ci/infra-deployments.git
        targetRevision: main
      destination:
        server: '{{server}}'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 50
          backoff:
            duration: 15s
