---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/konflux-ci/konflux-ci/dependencies/tekton-results?ref=dbd7f769d592549a6254ce603e8cbabe0801e319

patches:
  - patch: |
       - op: add
         path: /spec/template/spec/initContainers
         value:
          - name: volume-permissions
            image: busybox
            command: ['sh', '-c', 'chown -R 1001:1001 /bitnami']
            volumeMounts:
            - name: postgredb
              mountPath: /bitnami/postgresql
    target:
      kind: StatefulSet
      name: tekton-results-postgres              
