---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/konflux-ci/konflux-ci/dependencies/tekton-config?ref=6a391f0da1c12680bf5a0b2cc534cdd8cfa6fcea

patches:
  - patch: |
      - op: remove
        path: /spec/chain/options
    target:
      kind: TektonConfig
      name: config
  - patch: |
      - op: remove
        path: /spec/pipeline/options
    target:
      kind: TektonConfig
      name: config
