---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/konflux-ci/konflux-ci/dependencies/tekton-config?ref=e7d9e4373387710569457800ed88277084c2686e

patches:
  - patch: |
      - op: remove
        path: /spec/chain/options
    target:
      kind: TektonConfig
      name: config
  - patch: |
      - op: remove
        path: /spec/pipeline/options
    target:
      kind: TektonConfig
      name: config
