apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Core manifests
  - https://github.com/konflux-ci/konflux-ci/konflux-ci/integration/core?ref=a1541a09cbab822162c0c862a73660955403b2f8
  # CertManager manifests
  - https://github.com/konflux-ci/konflux-ci/konflux-ci/integration/certmanager?ref=a1541a09cbab822162c0c862a73660955403b2f8
